# Project Codebook
This file describes the format and values of the data sets for the following:
* input data used by the `run_analysis` function
* resulting tidy data set produced by the `run_analysis` function


## Input data

The following files from the Smartphone-Based Recognition of Human Activities and Postural Transitions Data Set are used by the `run_analysis` function.


### activity_labels.txt
Contains a mapping of the 6 activities perfomed by the subjects. Each record in this file describes a mapping from an Activity ID to Activity.

Records: 6                       
Record Length: 2

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1  | 1  | Activity ID  | Numeric values: 1 - 6  |
| V2  | 2  | Activity  | Character string in {WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING} |


### features.txt
Contains the names of the 561 features reported for each trial. Each record in this file describes a mapping from a feature ID to a feature function name and signature.

Records: 561                     
Record Length: 2

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1  | 1  | Feature ID  | Numeric values: 1 - 561  |
| V2  | 2  | Feature function  | Character string of the function name and signature used to generate the feature value. Example: `fBodyAccMag-mean()` |


### X_test.txt
Contains the feature values for the test trials. Each record in this file describes the feature data for one test trial.

Records: 2947                     
Record Length: 561

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1 - V561 | 1 - 561 | Feature value for a test trial | Numeric values in [-1,1] generated by a call to the function in the corresponding row of `features.txt`|


### y_test.txt
Contains the activity ID for the test trials. Each record in this file describes the activity for one test trial.

Records: 2947                     
Record Length: 1

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1 | 1 | Activity ID | Numeric values: 1 - 6. Foreign key into `activity_labels.txt`|


### subject_test.txt
Contains the subject ID for each test trial. Each record in this file describes the subject for one test trial.

Records: 2947                     
Record Length: 1

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1 | 1 | Subject ID | Numeric values: 1 - 30.|


### X_train.txt
Contains the feature values for the train trials. Each record in this file describes the feature data for one train trial.

Records: 7352                     
Record Length: 561

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1 - V561 | 1 - 561 | Feature value for a train trial | Numeric values in [-1,1] generated by a call to the function in the corresponding row of features.txt|


### y_train.txt
Contains the activity ID for the train trials. Each record in this file describes the activity for one train trial.

Records: 7352                     
Record Length: 1

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1 | 1 | Activity ID | Numeric values: 1 - 6. Foreign key into `activity_labels.txt`|


### subject_train.txt
Contains the subject ID for each train trial. Each record in this file describes the subject for one test trial.

Records: 7352                    
Record Length: 1

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| V1 | 1 | Subject ID | Numeric values: 1 - 30.|


## Project Result Data

The following file is generated from the run_analysis function.

### subjectByActivityFeatureMeans.txt
Contains the selected feature averages for each subject by activity. Each record in this file describes the averages of the 66 selected feature values for a subject by activity over all the trials performed by that subject for that activity.

Records: 180                   
Record Length: 68

| NAME  | POSITION  |  DESCRIPTION | VALUES OR EXPLANATION  |
|---|---|---|---|
| subject | 1 | Subject ID | Numeric values: 1 - 30.|
| activity | 2 | Activity | Character string in {WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING}|
| tBodyAccmeanX | 3 | Average of values for the Time domain - Body acceleration signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccmeanY | 4 | Average of values for the Time domain - Body acceleration signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccmeanZ | 5 | Average of values for the Time domain - Body acceleration signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccmeanX | 6 | Average of values for the Time domain - Gravity acceleration signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccmeanY | 7 | Average of values for the Time domain - Gravity acceleration signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccmeanZ | 8 | Average of values for the Time domain - Gravity acceleration signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkmeanX | 9 | Average of values for the Time domain - Body acceleration jerk signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkmeanY | 10 | Average of values for the Time domain - Body acceleration jerk signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkmeanZ | 11 | Average of values for the Time domain - Body acceleration jerk signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyromeanX | 12 | Average of values for the Time domain - Body gyroscope signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyromeanY | 13 | Average of values for the Time domain - Body gyroscope signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyromeanZ | 14 | Average of values for the Time domain - Body gyroscope signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkmeanX | 15 | Average of values for the Time domain - Body gyroscope jerk signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkmeanY | 16 | Average of values for the Time domain - Body gyroscope jerk signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkmeanZ | 17 | Average of values for the Time domain - Body gyroscope jerk signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccMagmean | 18 | Average of values for the Time domain - Body acceleration magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccMagmean | 19 | Average of values for the Time domain - Gravity acceleration magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkMagmean | 20 | Average of values for the Time domain - Body acceleration jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroMagmean | 21 | Average of values for the Time domain - Body gyroscope magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkMagmean | 22 | Average of values for the Time domain - Body gyroscope jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccmeanX | 23 | Average of values for the Frequency domain - Body acceleration signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccmeanY | 24 | Average of values for the Frequency domain - Body acceleration signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccmeanZ | 25 | Average of values for the Frequency domain - Body acceleration signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccJerkmeanX | 26 | Average of values for the Frequency domain - Body acceleration jerk signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccJerkmeanY | 27 | Average of values for the Frequency domain - Body acceleration jerk signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccJerkmeanZ | 28 | Average of values for the Frequency domain - Body acceleration jerk signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyGyromeanX | 29 | Average of values for the Frequency domain - Body gyroscope signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyGyromeanY | 30 | Average of values for the Frequency domain - Body gyroscope signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyGyromeanZ | 31 | Average of values for the Frequency domain - Body gyroscope signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccMagmean | 32 | Average of values for the Frequency domain - Body acceleration magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyBodyAccJerkMagmean | 33 | Average of values for the Frequency domain - Body acceleration jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyBodyGyroMagmean | 34 | Average of values for the Frequency domain - Body gyroscope magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyBodyGyroJerkMagmean | 35 | Average of values for the Frequency domain - Body gyroscope jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccstdX | 36 | Standard deviation of values for the Time domain - Body acceleration signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccstdY | 37 | Standard deviation of values for the Time domain - Body acceleration signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccstdZ | 38 | Standard deviation of values for the Time domain - Body acceleration signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccstdX | 39 | Standard deviation of values for the Time domain - Gravity acceleration signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccstdY | 40 | Standard deviation of values for the Time domain - Gravity acceleration signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccstdZ | 41 | Standard deviation of values for the Time domain - Gravity acceleration signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkstdX | 42 | Standard deviation of values for the Time domain - Body acceleration jerk signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkstdY | 43 | Standard deviation of values for the Time domain - Body acceleration jerk signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkstdZ | 44 | Standard deviation of values for the Time domain - Body acceleration jerk signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyrostdX | 45 | Standard deviation of values for the Time domain - Body gyroscope signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyrostdY | 46 | Standard deviation of values for the Time domain - Body gyroscope signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyrostdZ | 47 | Standard deviation of values for the Time domain - Body gyroscope signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkstdX | 48 | Standard deviation of values for the Time domain - Body gyroscope jerk signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkstdY | 49 | Standard deviation of values for the Time domain - Body gyroscope jerk signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkstdZ | 50 | Standard deviation of values for the Time domain - Body gyroscope jerk signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccMagstd | 51 | Standard deviation of values for the Time domain - Body acceleration magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tGravityAccMagstd | 52 | Standard deviation of values for the Time domain - Gravity acceleration magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyAccJerkMagstd | 53 | Standard deviation of values for the Time domain - Body acceleration jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroMagstd | 54 | Standard deviation of values for the Time domain - Body gyroscope magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| tBodyGyroJerkMagstd | 55 | Standard deviation of values for the Time domain - Body gyroscope jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccstdX | 56 | Standard deviation of values for the Frequency domain - Body acceleration signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccstdY | 57 | Standard deviation of values for the Frequency domain - Body acceleration signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccstdZ | 58 | Standard deviation of values for the Frequency domain - Body acceleration signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccJerkstdX | 59 | Standard deviation of values for the Frequency domain - Body acceleration jerk signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccJerkstdY | 60 | Standard deviation of values for the Frequency domain - Body acceleration jerk signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccJerkstdZ | 61 | Standard deviation of values for the Frequency domain - Body acceleration jerk signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyGyrostdX | 62 | Standard deviation of values for the Frequency domain - Body gyroscope signal in the X axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyGyrostdY | 63 | Standard deviation of values for the Frequency domain - Body gyroscope signal in the Y axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyGyrostdZ | 64 | Standard deviation of values for the Frequency domain - Body gyroscope signal in the Z axis feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyAccMagstd | 65 | Standard deviation of values for the Frequency domain - Body acceleration magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyBodyAccJerkMagstd | 66 | Standard deviation of values for the Frequency domain - Body acceleration jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyBodyGyroMagstd | 67 | Standard deviation of values for the Frequency domain - Body gyroscope magnitude feature for this subject and activity| Numeric values in [-1,1]. |
| fBodyBodyGyroJerkMagstd | 68 | of values for the Frequency domain - Body gyroscope jerk magnitude feature for this subject and activity| Numeric values in [-1,1]. | 
